### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by the6th** [suntabu/Markdown-Renderer-For-UIWidgets#3]
Can you clearly state the license of this repository?
Is it possible to get an MIT license?

Currently, I have a project to develop useful UIWidgets from dart library , etc.
https://github.com/the6th/UIWidgets.AddOns

I would like to include this Markdown library in it!
When we tried to clone  , there several parts did not work on Unity 2019.3.15f1.
I used this code as a base to fork and modify it, and then added the MIT License.

**Comment by suntabu** [comment]
Sorry for the late reply,  and absolutely yes for an MIT license.
