### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by kuro7766** [suntabu/Markdown-Renderer-For-UIWidgets#5]
Thank you for the great plugin!
But it seems that it doesn't work on webgl. On windows it's ok. 
I run your test c# code and it shows just a white Scaffold.

**Comment by suntabu** [comment]
Yes, It's never tested on WebGL, and for now, I have no time to support this.
Sorry for that.

If you are willing to support running on WebGL, please submit a PR, thanks.
